#logging:
#  level:
#    root: info
#
#enterprise:
#  name: sustech
#  age: 10
#  tel: 123456789
#  subjects:
#    - Java
#    - C++
#    - Python
#    - Go
#    - Kotlin

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projectII
#    username: postgres
#    password: 216122
    username: ljf
    password: 12011543


#spring:
#  profiles:
#    active: dev
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#
server:
  port: 8088